[package]
name = "task_graph"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
# rust-version.workspace = true

[workspace.package]
authors = ["Tigran Kirakosov <tkirakosov96@gmail.com>"]
edition = "2024"
version = "0.1.0"
license = "MIT OR Apache-2.0"
rust-version = "1.95.0"

[workspace]
resolver = "2"
members = [
    "graph",
    "macros",
    "bevy_task_graph",
]

[dependencies]
graph = { path = "graph", version = "0.1.0" }
macros = { path = "macros", version = "0.1.0" }
bevy_task_graph = { path = "bevy_task_graph", version = "0.1.0" }
