[package]
name = "action-orc"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[workspace.package]
authors = ["Tigran Kirakosov <tkirakosov96@gmail.com>"]
edition = "2024"
version = "0.1.0"
license = "MIT OR Apache-2.0"
rust-version = "1.95.0"

[workspace]
resolver = "2"
members = [
    "core",
    "engine",
    "macros",
]

[dependencies]
core = { path = "core", version = "0.1.0" }
engine = { path = "engine", version = "0.1.0" }
macros = { path = "macros", version = "0.1.0" }

[dev-dependencies]
trybuild = "1.0.121"
action-orc = { path = "." }

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
