[package]
name = "macros"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
winnow = "0.6"
syn = { version = "2.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"

[dev-dependencies]
insta = { version = "1.48.0", features = ["yaml"] }
trybuild = "1.0.120"
